version: '3.5'

services:
  frontend:
    build: ../1.10
    ports:
      - 5000:5000
  backend:
    build: ../1.11
    ports:
      - 8000:8000
    environment:
      - REDIS=redis
  redis:
    image: redis:latest
    ports:
      - 6379:6379
